// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1

// Defines values for AgentModeRequestMode.
const (
	AgentModeRequestModeConnected    AgentModeRequestMode = "connected"
	AgentModeRequestModeDisconnected AgentModeRequestMode = "disconnected"
)

// Defines values for AgentStatusConsoleConnection.
const (
	AgentStatusConsoleConnectionConnected    AgentStatusConsoleConnection = "connected"
	AgentStatusConsoleConnectionDisconnected AgentStatusConsoleConnection = "disconnected"
)

// Defines values for AgentStatusMode.
const (
	AgentStatusModeConnected    AgentStatusMode = "connected"
	AgentStatusModeDisconnected AgentStatusMode = "disconnected"
)

// Defines values for CollectorStatusStatus.
const (
	CollectorStatusStatusCollected  CollectorStatusStatus = "collected"
	CollectorStatusStatusCollecting CollectorStatusStatus = "collecting"
	CollectorStatusStatusConnected  CollectorStatusStatus = "connected"
	CollectorStatusStatusConnecting CollectorStatusStatus = "connecting"
	CollectorStatusStatusError      CollectorStatusStatus = "error"
	CollectorStatusStatusParsing    CollectorStatusStatus = "parsing"
	CollectorStatusStatusReady      CollectorStatusStatus = "ready"
)

// Defines values for InspectorStatusState.
const (
	InspectorStatusStateCanceled   InspectorStatusState = "canceled"
	InspectorStatusStateCanceling  InspectorStatusState = "canceling"
	InspectorStatusStateCompleted  InspectorStatusState = "completed"
	InspectorStatusStateError      InspectorStatusState = "error"
	InspectorStatusStateInitiating InspectorStatusState = "Initiating"
	InspectorStatusStateReady      InspectorStatusState = "ready"
	InspectorStatusStateRunning    InspectorStatusState = "running"
)

// Defines values for VMIssueCategory.
const (
	VMIssueCategoryAdvisory    VMIssueCategory = "Advisory"
	VMIssueCategoryCritical    VMIssueCategory = "Critical"
	VMIssueCategoryError       VMIssueCategory = "Error"
	VMIssueCategoryInformation VMIssueCategory = "Information"
	VMIssueCategoryOther       VMIssueCategory = "Other"
	VMIssueCategoryWarning     VMIssueCategory = "Warning"
)

// Defines values for VmInspectionStatusState.
const (
	VmInspectionStatusStateCanceled  VmInspectionStatusState = "canceled"
	VmInspectionStatusStateCompleted VmInspectionStatusState = "completed"
	VmInspectionStatusStateError     VmInspectionStatusState = "error"
	VmInspectionStatusStateNotFound  VmInspectionStatusState = "not_found"
	VmInspectionStatusStatePending   VmInspectionStatusState = "pending"
	VmInspectionStatusStateRunning   VmInspectionStatusState = "running"
)

// AgentModeRequest defines model for AgentModeRequest.
type AgentModeRequest struct {
	Mode AgentModeRequestMode `json:"mode"`
}

// AgentModeRequestMode defines model for AgentModeRequest.Mode.
type AgentModeRequestMode string

// AgentStatus defines model for AgentStatus.
type AgentStatus struct {
	// ConsoleConnection Current console connection status
	ConsoleConnection AgentStatusConsoleConnection `json:"console_connection"`

	// Error Connection error description
	Error *string `json:"error,omitempty"`

	// Mode Target mode for the agent
	Mode AgentStatusMode `json:"mode"`
}

// AgentStatusConsoleConnection Current console connection status
type AgentStatusConsoleConnection string

// AgentStatusMode Target mode for the agent
type AgentStatusMode string

// CollectorStartRequest defines model for CollectorStartRequest.
type CollectorStartRequest = VcenterCredentials

// CollectorStatus defines model for CollectorStatus.
type CollectorStatus struct {
	// Error Error message when status is error
	Error  *string               `json:"error,omitempty"`
	Status CollectorStatusStatus `json:"status"`
}

// CollectorStatusStatus defines model for CollectorStatus.Status.
type CollectorStatusStatus string

// GuestNetwork defines model for GuestNetwork.
type GuestNetwork struct {
	// Device Name of the network device inside the guest OS
	Device *string `json:"device,omitempty"`

	// Ip IP address assigned to this interface
	Ip *string `json:"ip,omitempty"`

	// Mac MAC address as seen by the guest OS
	Mac *string `json:"mac,omitempty"`

	// Network Network name as reported by the guest OS
	Network *string `json:"network,omitempty"`

	// PrefixLength Network prefix length (subnet mask in CIDR notation)
	PrefixLength *int32 `json:"prefixLength,omitempty"`
}

// InspectorStartRequest defines model for InspectorStartRequest.
type InspectorStartRequest struct {
	VcenterCredentials VcenterCredentials `json:"VcenterCredentials"`

	// VmIds Array of VirtualMachine id
	VmIds VMIdArray `json:"vmIds"`
}

// InspectorStatus defines model for InspectorStatus.
type InspectorStatus struct {
	// Error Error message when state is error
	Error *string `json:"error,omitempty"`

	// State Inspector state
	State InspectorStatusState `json:"state"`
}

// InspectorStatusState Inspector state
type InspectorStatusState string

// VMDevice defines model for VMDevice.
type VMDevice struct {
	// Kind Type of virtual device (e.g., cdrom, floppy, usb, serial, parallel)
	Kind *string `json:"kind,omitempty"`
}

// VMDisk defines model for VMDisk.
type VMDisk struct {
	// Bus Bus type (e.g., scsi, ide, sata, nvme)
	Bus *string `json:"bus,omitempty"`

	// Capacity Disk capacity in bytes
	Capacity *int64 `json:"capacity,omitempty"`

	// File Path to the VMDK file in the datastore
	File *string `json:"file,omitempty"`

	// Key Unique key identifying this disk within the VirtualMachine
	Key *int32 `json:"key,omitempty"`

	// Mode Disk mode (e.g., persistent, independent_persistent, independent_nonpersistent)
	Mode *string `json:"mode,omitempty"`

	// Rdm Whether this is a Raw Device Mapping (direct LUN access)
	Rdm *bool `json:"rdm,omitempty"`

	// Shared Whether this disk is shared between multiple VMs
	Shared *bool `json:"shared,omitempty"`
}

// VMIdArray Array of VirtualMachine id
type VMIdArray = []string

// VMIssue defines model for VMIssue.
type VMIssue struct {
	// Category Severity category of the issue. Unknown categories are mapped to 'Other'.
	Category VMIssueCategory `json:"category"`

	// Description Detailed description of the issue with additional context and recommendations
	Description *string `json:"description,omitempty"`

	// Id Unique identifier for this issue
	Id string `json:"id"`

	// Label Short label describing the issue
	Label string `json:"label"`
}

// VMIssueCategory Severity category of the issue. Unknown categories are mapped to 'Other'.
type VMIssueCategory string

// VMNIC defines model for VMNIC.
type VMNIC struct {
	// Index Index of the NIC within the VirtualMachine
	Index *int `json:"index,omitempty"`

	// Mac MAC address of the virtual NIC
	Mac *string `json:"mac,omitempty"`

	// Network Reference to the network this NIC is connected to
	Network *string `json:"network,omitempty"`
}

// VcenterCredentials defines model for VcenterCredentials.
type VcenterCredentials struct {
	Password string `json:"password"`

	// Url vCenter URL
	Url      string `json:"url"`
	Username string `json:"username"`
}

// VersionInfo defines model for VersionInfo.
type VersionInfo struct {
	// GitCommit Git commit SHA used to build the agent
	GitCommit string `json:"gitCommit"`

	// Version Agent version (e.g. v2.0.0)
	Version string `json:"version"`
}

// VirtualMachine defines model for VirtualMachine.
type VirtualMachine struct {
	// Cluster Cluster name
	Cluster string `json:"cluster"`

	// Datacenter Datacenter name
	Datacenter string `json:"datacenter"`

	// DiskSize Total disk size in MB
	DiskSize int64 `json:"diskSize"`

	// Id VirtualMachine ID in vCenter
	Id         string             `json:"id"`
	Inspection VmInspectionStatus `json:"inspection"`

	// IssueCount Number of issues found for this VirtualMachine
	IssueCount int `json:"issueCount"`

	// Memory Memory size in MB
	Memory int64 `json:"memory"`

	// Migratable True if the vm is migratable for MTV. False otherwise
	Migratable *bool `json:"migratable,omitempty"`

	// Name VirtualMachine name
	Name string `json:"name"`

	// Template True if the vm is a template. False otherwise
	Template *bool `json:"template,omitempty"`

	// VCenterState vCenter state (e.g., poweredOn, poweredOff, suspended)
	VCenterState string `json:"vCenterState"`
}

// VirtualMachineDetail defines model for VirtualMachineDetail.
type VirtualMachineDetail struct {
	// Cluster Name of the cluster containing the VirtualMachine
	Cluster *string `json:"cluster,omitempty"`

	// ConnectionState State of the connection between vCenter and the VirtualMachine's host (connected, disconnected, orphaned, or inaccessible)
	ConnectionState string `json:"connectionState"`

	// CoresPerSocket Number of CPU cores per virtual socket
	CoresPerSocket int32 `json:"coresPerSocket"`

	// CpuAffinity List of physical CPU IDs the VirtualMachine is pinned to for scheduling
	CpuAffinity *[]int32 `json:"cpuAffinity,omitempty"`

	// CpuCount Total number of virtual CPUs allocated to the VirtualMachine
	CpuCount int32 `json:"cpuCount"`

	// Datacenter Name of the datacenter containing the VirtualMachine
	Datacenter *string `json:"datacenter,omitempty"`

	// Devices List of other virtual devices attached to the VirtualMachine
	Devices *[]VMDevice `json:"devices,omitempty"`

	// Disks List of virtual disks attached to the VirtualMachine
	Disks []VMDisk `json:"disks"`

	// FaultToleranceEnabled Whether VMware Fault Tolerance is enabled, which maintains a live shadow VirtualMachine for instant failover
	FaultToleranceEnabled *bool `json:"faultToleranceEnabled,omitempty"`

	// Firmware Firmware type used by the VirtualMachine (bios or efi)
	Firmware *string `json:"firmware,omitempty"`

	// Folder Reference to the inventory folder containing the VirtualMachine
	Folder *string `json:"folder,omitempty"`

	// GuestId VMware identifier for the guest OS type (e.g., rhel8_64Guest)
	GuestId *string `json:"guestId,omitempty"`

	// GuestName Full name of the guest operating system as reported by VMware Tools
	GuestName *string `json:"guestName,omitempty"`

	// GuestNetworks Network configuration inside the guest OS as reported by VMware Tools
	GuestNetworks *[]GuestNetwork `json:"guestNetworks,omitempty"`

	// Host Reference to the ESXi host where the VirtualMachine is running
	Host *string `json:"host,omitempty"`

	// HostName Hostname of the guest OS as reported by VMware Tools
	HostName *string `json:"hostName,omitempty"`

	// Id Unique identifier for the VirtualMachine in vCenter
	Id         string              `json:"id"`
	Inspection *VmInspectionStatus `json:"inspection,omitempty"`

	// IpAddress Primary IP address of the guest OS as reported by VMware Tools
	IpAddress *string `json:"ipAddress,omitempty"`

	// Issues List of issues affecting this VirtualMachine
	Issues *[]VMIssue `json:"issues,omitempty"`

	// MemoryMB Amount of memory allocated to the VirtualMachine in megabytes
	MemoryMB int32 `json:"memoryMB"`

	// Migratable Whether the VirtualMachine can be migrated (true if no critical issues)
	Migratable *bool `json:"migratable,omitempty"`

	// Name Display name of the VirtualMachine
	Name string `json:"name"`

	// NestedHVEnabled Whether nested virtualization is enabled, allowing hypervisors to run inside the VirtualMachine
	NestedHVEnabled *bool `json:"nestedHVEnabled,omitempty"`

	// Nics List of virtual network interface cards attached to the VirtualMachine
	Nics []VMNIC `json:"nics"`

	// PowerState Current power state of the VirtualMachine (poweredOn, poweredOff, or suspended)
	PowerState string `json:"powerState"`

	// StorageUsed Total storage space consumed by the VirtualMachine in bytes
	StorageUsed *int64 `json:"storageUsed,omitempty"`

	// Template Whether the VirtualMachine is a template rather than a regular VirtualMachine
	Template *bool `json:"template,omitempty"`

	// ToolsRunningStatus Whether VMware Tools is currently running in the guest OS
	ToolsRunningStatus *string `json:"toolsRunningStatus,omitempty"`

	// ToolsStatus Installation status of VMware Tools (toolsNotInstalled, toolsNotRunning, toolsOld, toolsOk)
	ToolsStatus *string `json:"toolsStatus,omitempty"`

	// Uuid Universally unique identifier assigned by vCenter
	Uuid *string `json:"uuid,omitempty"`
}

// VirtualMachineListResponse defines model for VirtualMachineListResponse.
type VirtualMachineListResponse struct {
	// Page Current page number
	Page int `json:"page"`

	// PageCount Total number of pages
	PageCount int `json:"pageCount"`

	// Total Total number of VMs matching the filter
	Total int              `json:"total"`
	Vms   []VirtualMachine `json:"vms"`
}

// VmInspectionStatus defines model for VmInspectionStatus.
type VmInspectionStatus struct {
	// Error Error message when state is error
	Error *string `json:"error,omitempty"`

	// Results Inspection results
	Results *map[string]interface{} `json:"results,omitempty"`

	// State Current inspection state
	State VmInspectionStatusState `json:"state"`
}

// VmInspectionStatusState Current inspection state
type VmInspectionStatusState string

// GetInventoryParams defines parameters for GetInventory.
type GetInventoryParams struct {
	// WithAgentId If true, include the agentId in the response (Compatible with manual inventory upload).
	WithAgentId *bool `form:"withAgentId,omitempty" json:"withAgentId,omitempty"`
}

// GetVMsParams defines parameters for GetVMs.
type GetVMsParams struct {
	// MinIssues Filter VMs with at least this many issues
	MinIssues *int `form:"minIssues,omitempty" json:"minIssues,omitempty"`

	// Clusters Filter by clusters (OR logic - matches VMs in any of the specified clusters)
	Clusters *[]string `form:"clusters,omitempty" json:"clusters,omitempty"`

	// DiskSizeMin Minimum disk size in MB
	DiskSizeMin *int64 `form:"diskSizeMin,omitempty" json:"diskSizeMin,omitempty"`

	// DiskSizeMax Maximum disk size in MB
	DiskSizeMax *int64 `form:"diskSizeMax,omitempty" json:"diskSizeMax,omitempty"`

	// MemorySizeMin Minimum memory size in MB
	MemorySizeMin *int64 `form:"memorySizeMin,omitempty" json:"memorySizeMin,omitempty"`

	// MemorySizeMax Maximum memory size in MB
	MemorySizeMax *int64 `form:"memorySizeMax,omitempty" json:"memorySizeMax,omitempty"`

	// Status Filter by status (OR logic - matches VMs with any of the specified statuses)
	Status *[]string `form:"status,omitempty" json:"status,omitempty"`

	// Sort Sort fields with direction (e.g., "name:asc" or "cluster:desc,name:asc"). Valid fields are name, vCenterState, cluster, diskSize, memory, issues.
	Sort *[]string `form:"sort,omitempty" json:"sort,omitempty"`

	// Page Page number for pagination
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of items per page
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// SetAgentModeJSONRequestBody defines body for SetAgentMode for application/json ContentType.
type SetAgentModeJSONRequestBody = AgentModeRequest

// StartCollectorJSONRequestBody defines body for StartCollector for application/json ContentType.
type StartCollectorJSONRequestBody = CollectorStartRequest

// AddVMsToInspectionJSONRequestBody defines body for AddVMsToInspection for application/json ContentType.
type AddVMsToInspectionJSONRequestBody = VMIdArray

// StartInspectionJSONRequestBody defines body for StartInspection for application/json ContentType.
type StartInspectionJSONRequestBody = InspectorStartRequest
